env:
  global:
    - CC_TEST_REPORTER_ID=14674c41ef6ea023bd25bb5af6fe05263afe31d5dba8baaf0f2c0c01ad1c26ab
language: csharp
mono: none
dotnet: 3.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - dotnet restore
  - dotnet build
  - dotnet test Wumpus.csproj /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat=cobertura /p:ExcludeByFile=\"**/Microsoft.NET.Test.Sdk.Program.cs\" /p:CoverletOutput='./cobertura.xml'
after_script:
  - ./cc-test-reporter format-coverage -t cobertura --prefix "/home/travis/build/eduardoafontana/poa-final-project"
  - ./cc-test-reporter after-build -t cobertura --exit-code $TRAVIS_TEST_RESULT --debug