services: mongodb
language: csharp
mono: none
dotnet: 3.1
script:
 - dotnet restore
 - dotnet build
addons:
  code_climate:
    repo_token: 14674c41ef6ea023bd25bb5af6fe05263afe31d5dba8baaf0f2c0c01ad1c26ab
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info